kv_namespaces = [
  { binding = "CACHE", id = "338fbd66700647869007ccc2c57fe08d" }
]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "sso"
database_id = "5b8d49f4-9296-4c04-99e5-6fc30b426952"
