name = "v0-sso-web"
compatibility_date = "2023-10-30"
compatibility_flags = [ "nodejs_compat" ]
main = "./.cloudflare/worker.js"

routes = [
  # { pattern = "sso.willin.wang", custom_domain = true },
	{ pattern = "sso.v0.md", custom_domain = true }
]
site = { bucket = "./.cloudflare/public" }
build = { command = "bun run build" }

[env.dev]
workers_dev = true
