name = "v0-sso-web"
compatibility_date = "2023-10-30"
compatibility_flags = [ "nodejs_compat" ]
main = "./.cloudflare/worker.js"

[site]
bucket = "./.cloudflare/public"

[build]
command = "npm run build"

[env.dev]
workers_dev = true
